spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/board
    username: board
    password: board123
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      encoding: UTF-8
      schema-locations: classpath:schema.sql

  thymeleaf:
    cache: false

  mvc:
    hiddenmethod:
      filter:
        enabled: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.board.domain
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: 'NULL'

server:
  port: 8080

logging:
  level:
    com.example.board: debug
